inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  NewCops: enable

RSpec/NestedGroups:
  Max: 4

# Since using `aggregate_failures` metadata.
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: require_implicit

RSpec/ExampleLength:
  Enabled: false
